"""Write through real Windows clipboard, OCR and keyboard into our own WPF grid."""
import platform
import subprocess
import time
import uuid
from types import SimpleNamespace

import pytest

from rpa_orkestrai.desktop.controller import DesktopController
from rpa_orkestrai.desktop.screen_tables import screen_table_cell
from rpa_orkestrai.desktop.tables import UiaTables
from rpa_orkestrai.desktop.windows import Win32Windows, WindowService

pytestmark = pytest.mark.skipif(platform.system() != 'Windows', reason='Real Windows table editing')


@pytest.mark.parametrize('header,width,edit_mode,method', [
    (False, 140, 'f2', 'screen'), (False, 280, 'double_click', 'screen'),
    (True, 140, 'double_click', 'screen'), (True, 280, 'f2', 'screen'),
    (False, 280, 'double_click', 'point'), (False, 140, 'f2', 'point-copy'),
    (True, 140, 'double_click', 'point-copy'), (True, 280, 'double_click', 'point-shape'),
    (False, 280, 'auto', 'point-copy'), (True, 140, 'auto', 'point-copy'),
    (True, 280, 'auto', 'point-prefix'),
])
def test_screen_write_uses_real_grid_clipboard_with_optional_headers(tmp_path, monkeypatch,
                                                                    header, width, edit_mode, method):
    title = 'RpaOrkestrAI screen grid ' + uuid.uuid4().hex
    script = tmp_path / 'screen-grid.ps1'
    source = '''Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName System.Data
$window = New-Object System.Windows.Window
$window.Title = "TITLE"
$window.Width = 780
$window.Height = 320
$window.Left = 40
$window.Top = 40
$window.WindowStartupLocation = 'Manual'
$grid = New-Object System.Windows.Controls.DataGrid
$grid.AutoGenerateColumns = $true
$grid.CanUserAddRows = $false
$grid.IsReadOnly = $false
$grid.FontSize = 16
$grid.RowHeight = 32
$grid.SelectionUnit = 'CellOrRowHeader'
$grid.SelectionMode = 'Extended'
$grid.ClipboardCopyMode = 'COPYMODE'
[System.Windows.Automation.AutomationProperties]::SetAutomationId($grid, 'screenGrid')
$table = New-Object System.Data.DataTable
[void]$table.Columns.Add('Code')
[void]$table.Columns.Add('Status')
[void]$table.Columns.Add('Count')
[void]$table.Rows.Add('A125', 'OLD', '1')
[void]$table.Rows.Add('A126', 'OLD', '1')
$grid.Add_AutoGeneratedColumns({
    $grid.Columns[0].Width = [System.Windows.Controls.DataGridLength]::new(COLWIDTH)
    $grid.Columns[1].Width = [System.Windows.Controls.DataGridLength]::new(180)
    $grid.Columns[2].Width = [System.Windows.Controls.DataGridLength]::new(100)
})
EXPORTPREFIX
$grid.ItemsSource = $table.DefaultView
$window.Content = $grid
[void]$window.ShowDialog()
'''
    # Our test application's clipboard export adds an empty record before its
    # headings, as some grids do. Single-cell editor copying is unchanged.
    prefix = """$grid.AddHandler([System.Windows.Input.CommandManager]::PreviewExecutedEvent,
    [System.Windows.Input.ExecutedRoutedEventHandler]{ param($sender, $eventArgs)
        if ($eventArgs.Command -eq [System.Windows.Input.ApplicationCommands]::Copy -and
            $eventArgs.OriginalSource -isnot [System.Windows.Controls.TextBox] -and
            $grid.SelectedCells.Count -eq 6) {
            $lines = @("`t`t", "Code`tStatus`tCount")
            foreach ($record in $table.Rows) { $lines += ($record.ItemArray -join "`t") }
            [System.Windows.Clipboard]::SetText(($lines -join "`r`n"))
            $eventArgs.Handled = $true
        }
    })""" if method == 'point-prefix' else ''
    source = source.replace('EXPORTPREFIX', prefix)
    header_row = 2 if method == 'point-prefix' else 1
    script.write_text(source.replace('TITLE', title).replace('COLWIDTH', str(width))
                      .replace('COPYMODE', 'IncludeHeader' if header else 'ExcludeHeader'), encoding='utf-8-sig')
    process = subprocess.Popen(['powershell.exe', '-NoProfile', '-STA', '-ExecutionPolicy', 'Bypass',
                                '-File', str(script)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    try:
        windows, backend = Win32Windows(), UiaTables()
        deadline, grids = time.monotonic() + 30, []
        while time.monotonic() < deadline:
            assert process.poll() is None, process.communicate()[1].decode(errors='replace')
            found = [w for w in windows.list_windows() if w.title == title]
            if found:
                window = found[0]
                grids = backend.tables(window, lambda: None)
                if grids and grids[0].shape() == (2, 3):
                    break
            time.sleep(.2)
        assert len(grids) == 1 and grids[0].shape() == (2, 3)
        assert grids[0].cell(0, 0).info().width == pytest.approx(width, abs=3)
        service = WindowService(backend=windows)
        service.focus(window.result())
        info = grids[0].info()
        region = (info.x - window.x, info.y - window.y, info.width, info.height)
        # The fail-safe stays enabled. Put the pointer inside this test window,
        # since a fresh CI desktop can start it in the emergency corner.
        import ctypes
        ctypes.windll.user32.SetCursorPos(*info.center)
        reports = []
        options = dict(selection=dict(table='', row_mode='index', row=2, column='sutun_2',
                                      match_column='', match_value=''), value='READY', header=header,
                       edit_mode=edit_mode, report=reports.append, header_row=header_row)
        if method == 'screen':
            result = screen_table_cell(service, window.result(), DesktopController(), region=region, **options)
        else:
            if method in {'point-copy', 'point-prefix'}:
                monkeypatch.setattr('rpa_orkestrai.desktop.tables.native_backend',
                                    lambda: SimpleNamespace(tables=lambda *args: []))
            elif method == 'point-shape':
                monkeypatch.setattr('rpa_orkestrai.desktop.tables.UiaCell.write_available', lambda self: False)
                options['header'] = False  # Native shape must detect the actual copied titles.
            x, y = grids[0].cell(0, 0).info().center
            x, y = x - window.x, y - window.y
            structure = service.inspect_table(window.result(), DesktopController(), x=x, y=y, header=header, header_row=header_row)
            assert structure['rows'] == 2 and len(structure['columns']) == 3
            if edit_mode == 'auto':
                import threading

                from rpa_orkestrai.config import Settings
                from rpa_orkestrai.engine import Executor
                from rpa_orkestrai.models import Run, Step, Workflow
                from rpa_orkestrai.storage import Store
                options['value'] = 'Değişkenden gelen uzun hücre değeri ' * 5 + 'TAMAMLANDI'
                workflow = Workflow(name='Tablo değişken testi', steps=[Step(action='window.write_table', params={
                    'window': '${target}', 'write_method': 'point', 'target_mode': 'coordinates',
                    'x': x, 'y': y, 'row': '${record.row}', 'column': 'sutun_2', 'header': header,
                    'header_row': header_row, 'value': '${record.value}', 'output': 'written'})])
                run = Run(workflow_id=workflow.id, workflow_name=workflow.name, department=workflow.department)
                executor = Executor(Settings(tmp_path / 'runtime', dotenv=False), Store(tmp_path / 'runtime'),
                    run, threading.Event(), lambda: None, variables={'target': window.result(),
                    'record': {'row': 2, 'value': options['value']}})
                executor._windows, executor._desktop = service, DesktopController()
                executor.execute(workflow)
                result = executor.variables['written']
            else:
                result = service.point_table_cell(window.result(), DesktopController(), targeting=dict(x=x, y=y), **options)
        assert result == {'row': 2, 'column': 2, 'value': options['value']}
        if method != 'point' and edit_mode != 'auto':
            assert reports[0]['current_value'] == 'OLD' and reports[0]['rows'] == 2
        # Independent native reads prove which real cell changed; the writer
        # itself uses no UIA row/column addressing or accessibility value write.
        assert grids[0].cell(0, 1).read() == 'OLD'
        assert grids[0].cell(1, 1).read() == options['value']
        assert grids[0].cell(1, 0).read() == 'A126'
    finally:
        process.terminate()
        process.communicate(timeout=15)
