"""Write through real Windows clipboard, OCR and keyboard into our own WPF grid."""
import platform
import subprocess
import time
import uuid

import pytest

from rpa_orkestrai.desktop.controller import DesktopController
from rpa_orkestrai.desktop.screen_tables import screen_table_cell
from rpa_orkestrai.desktop.tables import UiaTables
from rpa_orkestrai.desktop.windows import Win32Windows, WindowService

pytestmark = pytest.mark.skipif(platform.system() != 'Windows', reason='Real Windows table editing')


@pytest.mark.parametrize('header,width,edit_mode', [(False, 140, 'f2'), (False, 280, 'double_click'),
                                                   (True, 140, 'double_click'), (True, 280, 'f2')])
def test_screen_write_uses_real_grid_clipboard_with_optional_headers(tmp_path, header, width, edit_mode):
    title = 'RpaOrkestrAI screen grid ' + uuid.uuid4().hex
    script = tmp_path / 'screen-grid.ps1'
    source = '''Add-Type -AssemblyName PresentationFramework
Add-Type -AssemblyName System.Data
$window = New-Object System.Windows.Window
$window.Title = "TITLE"
$window.Width = 780
$window.Height = 320
$window.Left = 40
$window.Top = 40
$window.WindowStartupLocation = 'Manual'
$grid = New-Object System.Windows.Controls.DataGrid
$grid.AutoGenerateColumns = $true
$grid.CanUserAddRows = $false
$grid.IsReadOnly = $false
$grid.FontSize = 16
$grid.RowHeight = 32
$grid.SelectionUnit = 'CellOrRowHeader'
$grid.SelectionMode = 'Extended'
$grid.ClipboardCopyMode = 'COPYMODE'
[System.Windows.Automation.AutomationProperties]::SetAutomationId($grid, 'screenGrid')
$table = New-Object System.Data.DataTable
[void]$table.Columns.Add('Code')
[void]$table.Columns.Add('Status')
[void]$table.Columns.Add('Count')
[void]$table.Rows.Add('A125', 'OLD', '1')
[void]$table.Rows.Add('A126', 'OLD', '1')
$grid.Add_AutoGeneratedColumns({
    $grid.Columns[0].Width = [System.Windows.Controls.DataGridLength]::new(COLWIDTH)
    $grid.Columns[1].Width = [System.Windows.Controls.DataGridLength]::new(180)
    $grid.Columns[2].Width = [System.Windows.Controls.DataGridLength]::new(100)
})
$grid.ItemsSource = $table.DefaultView
$window.Content = $grid
[void]$window.ShowDialog()
'''
    script.write_text(source.replace('TITLE', title).replace('COLWIDTH', str(width))
                      .replace('COPYMODE', 'IncludeHeader' if header else 'ExcludeHeader'), encoding='utf-8-sig')
    process = subprocess.Popen(['powershell.exe', '-NoProfile', '-STA', '-ExecutionPolicy', 'Bypass',
                                '-File', str(script)], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    try:
        windows, backend = Win32Windows(), UiaTables()
        deadline, grids = time.monotonic() + 30, []
        while time.monotonic() < deadline:
            assert process.poll() is None, process.communicate()[1].decode(errors='replace')
            found = [w for w in windows.list_windows() if w.title == title]
            if found:
                window = found[0]
                grids = backend.tables(window, lambda: None)
                if grids and grids[0].shape() == (2, 3):
                    break
            time.sleep(.2)
        assert len(grids) == 1 and grids[0].shape() == (2, 3)
        assert grids[0].cell(0, 0).info().width == pytest.approx(width, abs=3)
        service = WindowService(backend=windows)
        service.focus(window.result())
        info = grids[0].info()
        region = (info.x - window.x, info.y - window.y, info.width, info.height)
        # The fail-safe stays enabled. Put the pointer inside this test window,
        # since a fresh CI desktop can start it in the emergency corner.
        import ctypes
        ctypes.windll.user32.SetCursorPos(*info.center)
        reports = []
        result = screen_table_cell(service, window.result(), DesktopController(), region=region,
                                   selection=dict(row_mode='index', row=2, column='sutun_2',
                                                  match_column='', match_value=''),
                                   value='READY', header=header, edit_mode=edit_mode, report=reports.append)
        assert result == {'row': 2, 'column': 2, 'value': 'READY'}
        assert reports[0]['current_value'] == 'OLD' and reports[0]['rows'] == 2
        # Independent native reads prove which real cell changed; the writer
        # itself uses no UIA row/column addressing or accessibility value write.
        assert grids[0].cell(0, 1).read() == 'OLD'
        assert grids[0].cell(1, 1).read() == 'READY'
        assert grids[0].cell(1, 0).read() == 'A126'
    finally:
        process.terminate()
        process.communicate(timeout=15)
